# Generated by Django 2.1.7 on 2019-04-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_auto_20190313_1132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecturer',
            old_name='lecturer_modules',
            new_name='lecturerModules',
        ),
        migrations.RemoveField(
            model_name='lecturer',
            name='name',
        ),
        migrations.AddField(
            model_name='student',
            name='is_student',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.CharField(choices=[('5', 'PhD Student'), ('2', 'Second Year Student'), ('3', 'Third Year Student'), ('4', 'Masters Student')], default='', max_length=1),
        ),
    ]
