# Generated by Django 2.1.7 on 2019-04-12 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0004_auto_20190412_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year_of_study',
            field=models.CharField(choices=[('4', 'Masters Student'), ('3', 'Third Year Student'), ('2', 'Second Year Student'), ('5', 'PhD Student')], default='', max_length=1),
        ),
    ]
